from setuptools import setup

setup(
    name='vcflat',
    version='0.1.0',
    packages=['venv.lib.python3.7.distutils', 'venv.lib.python3.7.encodings', 'venv.lib.python3.7.importlib',
              'venv.lib.python3.7.collections', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.network',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations',
              'venv.lib.python3.7.site-packages.pip._internal.distributions',
              'venv.lib.python3.7.site-packages.pip._internal.distributions.source',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.click',
              'venv.lib.python3.7.site-packages.numpy', 'venv.lib.python3.7.site-packages.numpy.ma',
              'venv.lib.python3.7.site-packages.numpy.ma.tests', 'venv.lib.python3.7.site-packages.numpy.doc',
              'venv.lib.python3.7.site-packages.numpy.fft', 'venv.lib.python3.7.site-packages.numpy.fft.tests',
              'venv.lib.python3.7.site-packages.numpy.lib', 'venv.lib.python3.7.site-packages.numpy.lib.tests',
              'venv.lib.python3.7.site-packages.numpy.core', 'venv.lib.python3.7.site-packages.numpy.core.tests',
              'venv.lib.python3.7.site-packages.numpy.f2py', 'venv.lib.python3.7.site-packages.numpy.f2py.tests',
              'venv.lib.python3.7.site-packages.numpy.tests', 'venv.lib.python3.7.site-packages.numpy.compat',
              'venv.lib.python3.7.site-packages.numpy.compat.tests', 'venv.lib.python3.7.site-packages.numpy.linalg',
              'venv.lib.python3.7.site-packages.numpy.linalg.tests', 'venv.lib.python3.7.site-packages.numpy.random',
              'venv.lib.python3.7.site-packages.numpy.random.tests',
              'venv.lib.python3.7.site-packages.numpy.random.tests.data',
              'venv.lib.python3.7.site-packages.numpy.testing', 'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.wheel',
              'venv.lib.python3.7.site-packages.wheel.cli', 'venv.lib.python3.7.site-packages.Cython',
              'venv.lib.python3.7.site-packages.Cython.Plex', 'venv.lib.python3.7.site-packages.Cython.Build',
              'venv.lib.python3.7.site-packages.Cython.Build.Tests', 'venv.lib.python3.7.site-packages.Cython.Tests',
              'venv.lib.python3.7.site-packages.Cython.Runtime', 'venv.lib.python3.7.site-packages.Cython.Tempita',
              'venv.lib.python3.7.site-packages.Cython.Utility', 'venv.lib.python3.7.site-packages.Cython.Compiler',
              'venv.lib.python3.7.site-packages.Cython.Compiler.Tests',
              'venv.lib.python3.7.site-packages.Cython.Debugger',
              'venv.lib.python3.7.site-packages.Cython.Debugger.Tests',
              'venv.lib.python3.7.site-packages.Cython.Distutils', 'venv.lib.python3.7.site-packages.cyvcf2',
              'venv.lib.python3.7.site-packages.cyvcf2.tests', 'venv.lib.python3.7.site-packages.pandas',
              'venv.lib.python3.7.site-packages.pandas.io', 'venv.lib.python3.7.site-packages.pandas.io.sas',
              'venv.lib.python3.7.site-packages.pandas.io.json', 'venv.lib.python3.7.site-packages.pandas.io.excel',
              'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.ops', 'venv.lib.python3.7.site-packages.pandas.core.util',
              'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.internals',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.excel',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.tests.io.pytables',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.config',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.window',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.holiday',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.frequencies',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.resample',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.list',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.arithmetic',
              'venv.lib.python3.7.site-packages.pandas.tests.reductions',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.arrays', 'venv.lib.python3.7.site-packages.pandas.compat',
              'venv.lib.python3.7.site-packages.pandas.compat.numpy', 'venv.lib.python3.7.site-packages.pandas.errors',
              'venv.lib.python3.7.site-packages.pandas._config', 'venv.lib.python3.7.site-packages.pandas.tseries',
              'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.pandas.plotting._matplotlib',
              'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
              'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.7.site-packages.pyximport', 'venv.lib.python3.7.site-packages.setuptools',
              'venv.lib.python3.7.site-packages.setuptools.extern',
              'venv.lib.python3.7.site-packages.setuptools._vendor',
              'venv.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.7.site-packages.setuptools.command', 'venv.lib.python3.7.site-packages.coloredlogs',
              'venv.lib.python3.7.site-packages.coloredlogs.converter',
              'venv.lib.python3.7.site-packages.humanfriendly', 'venv.lib.python3.7.site-packages.pkg_resources',
              'venv.lib.python3.7.site-packages.pkg_resources.extern',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor.packaging', 'vcflat', 'vcflat.tests'],
    url='',
    license='MIT',
    author='Aron Skaftason',
    author_email='arontommi@gmail.com',
    description='Simple parsing of vcf files'
)
